---
title: 'Class 6: R functions'
author: "Suzanna Kwak"
date: "4/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **class 6** r markdown document with my *code* and notes for the day. 

```{r}
plot(1:10, type = "l", col="blue")
```

```{r}
read.csv("test1.txt", header=TRUE)
```

```{r}
read.table("test2.txt", header=TRUE, sep="$")
```

```{r}
read.table("test3.txt", header=FALSE)
```

## Functions
```{r}
add <- function(x, y=1) {
  #Body!
  x+y
  }
```

```{r}
add( x=c(1,2,3), y=4)
```

```{r}
add(10)
```

```{r}
#add(1,2,2)
```


## Another Example
```{r}
rescale <- function(x) {
 rng <-range(x,na.rm=TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
rescale(c(1,2,NA,3,10))
```

```{r}
#rescale(c(1,10,"string"))
```

```{r}
x <- c(1,10, "string")

is.numeric (x)


```


```{r}
x <- c(1,2,3,NA,10)
 rng <-range(x, na.rm=TRUE)
 rng
#(x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale2 <- function(x) {
  
  if(!is.numeric(x)) {stop("you need cheese")}
 rng <-range(x,na.rm=na.rm)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
  return(answer)
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
   print("please don't sing again")
 }
 print("I can see it in ...")
}
```

```{r}
rescale3( c(1,3,NA,10))
```

```{r}
rescale3( c(1,3,NA,10), plot=TRUE)
```

