---
title: "Class 6 Homework"
author: "Suzanna Kwak"
date: "4/23/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Improve this analysis Code
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

## Start with a working code snippet

```{r}
s1 <- read.pdb("4AKE")
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
```

## Simplify the snippets by giving a generic name 'x' to protein file and changing 's1' to 'prt'

```{r}
#prt <- read.pdb(x)
#prt.chainA <- trim.pdb(prt,chain="A", elety="CA")
#prt.b <- prt.chainA$atom$b
#plotb3(prt.b, sse=prt.chainA, typ="l", ylab="Bfactor")
```

## Turn it into a function
```{r}
analyze.prt <- function(x) {
    prt <- read.pdb(x)
    prt.chainA <- trim.pdb(prt,chain="A", elety="CA")
    prt.b <- prt.chainA$atom$b
    plotb3(prt.b, sse=prt.chainA, typ="l", ylab="Bfactor")
}

```

## try the function
```{r}
analyze.prt("4AKE")
analyze.prt("1AKE")
analyze.prt("1E4Y")
```


